services:
  - type: web
    name: grocery-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx500m -Xms500m"
      - key: PORT
        value: 8080
      - key: DOCKER_BUILDKIT
        value: "0"
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.jifrtixjovwxoxkisnzk&password=Grocery@123.#
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: Grocery@123.#
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
         value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY
        value: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
      - key: APP_AUTH_DEVELOPMENT_MODE
        value: "false"
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - Dockerfile