services:
  - type: web
    name: grocery-backend
    env: docker
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx500m -Xms500m"
      - key: PORT
        value: 8080
    buildCommand: docker build -t grocery-backend .
    startCommand: docker run -p $PORT:8080 grocery-backend 