services:
  - type: web
    name: grocery-backend
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx500m -Xms500m"
      - key: PORT
        value: 8080
      - key: DOCKER_BUILDKIT
        value: "0"
      - key: DATABASE_URL
        value: jdbc:mysql://root:lXMmSbkCNDnDSqhIRRQpOzoIBAHNZfaV@interchange.proxy.rlwy.net:52270/railway
      - key: MYSQL_USERNAME  
        value: root
      - key: MYSQL_PASSWORD
        value: lXMmSbkCNDnDSqhIRRQpOzoIBAHNZfaV
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - Dockerfile 